version: '3'
services:
  sdrangel:
    image: "sdrangel/${SDRANGEL_FLAVOR}:${IMAGE_VERSION}"
    container_name: "sdrangel_${NAME_SUFFIX}"
    dns: "${DNS}"
    environment:
      - PULSE_SERVER=unix:/run/user/${USER_UID}/pulse/native
      - DISPLAY=unix:0.0
      - FFTWFILE=${FFTWFILE}
      - IPADDR=${IPADDR}
      - APIPORT=${API_PORT}
    volumes:
      - "/home/${USER}/.config:/home/sdr/.config:rw"
      - "/run/user/${USER_UID}/pulse:/run/user/${USER_UID}/pulse"
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
  sdrangelcli:
    image: "sdrangelcli:${IMAGE_VERSION_CLI}"
    container_name: "sdrangelcli_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${WEB_PORT}:8080"
    networks:
      default:
        ipv4_address: 172.18.0.3
  sdrangelspectrum:
    image: "sdrangelspectrum:${IMAGE_VERSION_SPEC}"
    container_name: "sdrangelspectrum_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${SPEC_PORT}:8081"
    networks:
      default:
        ipv4_address: 172.18.0.4
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.0/16

