version: '3'
services:
  sdrangel:
    image: "sdrangel/${BRANCH_NAME}:${IMAGE_VERSION}"
    container_name: "sdrangel_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${SSH_PORT}:22"
      - "${API_PORT}:8091"
      - "${UDP_PORT}:${UDP_PORT}/udp"
    expose:
      - "8091"
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - DISPLAY=unix:0.0
    volumes:
      - "/home/${USER}/.config:/home/sdr/.config:rw"
      - "/run/user/${USER_UID}/pulse:/run/user/1000/pulse"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      default:
        ipv4_address: 172.18.0.12
    privileged: true
    stdin_open: true
    tty: true
  sdrangelcli:
    image: sdrangelcli/node:latest
    container_name: "sdrangelcli_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${WEB_PORT}:8080"
    networks:
      default:
        ipv4_address: 172.18.0.13
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.0/16

