version: '3'
services:
  sdrangel:
    image: "sdrangel/bionic:server${RX_BITS}"
    container_name: "sdrangel_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${SSH_PORT}:22"
      - "${API_PORT}:8091"
      - "${UDP_PORT}:${UDP_PORT}/udp"
    expose:
      - "8091"
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - "/home/${USER}/.config:/home/sdr/.config:rw"
      - "/run/user/${USER_UID}/pulse:/run/user/1000/pulse"
    privileged: true
    stdin_open: true
    tty: true
  sdrangelcli:
    image: sdrangelcli/node:latest
    container_name: "sdrangelcli_${NAME_SUFFIX}"
    dns: "${DNS}"
    ports:
      - "${WEB_PORT}:8080"
